### ISSUE TITLE
"Restart" button doesn't work in 10.11 NBI

### ISSUE THREAD

**Issue by erikberglund** [grahamgilbert/imagr#102]
I get this message after a workflow completed and i tried pressing "Restart"

10.11 beta 7 NBI built with NBICreator:

2015-09-02 06:40:32.967 Imagr[844:18829] <type 'exceptions.AttributeError'>: 'str' object has no attribute 'SetStartupDisk'
2015-09-02 06:40:32.977 Imagr[844:18829] 
    0   CoreFoundation                      0x0000000106cf3a22 __exceptionPreprocess + 178
    1   libobjc.A.dylib                     0x0000000106744f7e objc_exception_throw + 48
    2   CoreFoundation                      0x0000000106cf35b9 -[NSException raise] + 9
    3   _objc.so                            0x0000000113779ba4 PyObjCErr_ToObjCWithGILState + 46
    4   _objc.so                            0x0000000113766792 PyObjCFFI_MakeClosure + 5033
    5   libffi.dylib                        0x00000001072b6a24 ffi_closure_unix64_inner + 516
    6   libffi.dylib                        0x00000001072b6096 ffi_closure_unix64 + 70
    7   AppKit                              0x0000000107b7f5e8 -[NSWindow _endWindowBlockingModalSession:returnCode:] + 315
    8   AppKit                              0x0000000107c09a3b -[NSAlert buttonPressed:] + 107
    9   libsystem_trace.dylib               0x000000010773e082 _os_activity_initiate + 75
    10  AppKit                              0x0000000107b53685 -[NSApplication sendAction:to:from:] + 460
    11  AppKit                              0x0000000107b685e6 -[NSControl sendAction:to:] + 86
    12  AppKit                              0x0000000107b68510 __26-[NSCell _sendActionFrom:]_block_invoke + 131
    13  libsystem_trace.dylib               0x000000010773e082 _os_activity_initiate + 75
    14  AppKit                              0x0000000107b6846d -[NSCell _sendActionFrom:] + 144
    15  libsystem_trace.dylib               0x000000010773e082 _os_activity_initiate + 75
    16  AppKit                              0x0000000107b66a92 -[NSCell trackMouse:inRect:ofView:untilMouseUp:] + 2693
    17  AppKit                              0x0000000107bbbfe0 -[NSButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 744
    18  AppKit                              0x0000000107b651bc -[NSControl mouseDown:] + 669
    19  AppKit                              0x0000000108111b5d -[NSWindow _handleMouseDownEvent:isDelayedEvent:] + 6322
    20  AppKit                              0x0000000108112ded -[NSWindow _reallySendEvent:isDelayedEvent:] + 212
    21  AppKit                              0x0000000107a6c795 -[NSWindow sendEvent:] + 517
    22  AppKit                              0x0000000107a68eb7 -[NSApplication sendEvent:] + 2540
    23  AppKit                              0x000000010799c12a -[NSApplication run] + 796
    24  AppKit                              0x000000010791e396 NSApplicationMain + 1176
    25  _AppKit.so                          0x0000000114327926 init_AppKit + 1117
    26  Python                              0x0000000106077a0b PyEval_EvalFrameEx + 13400
    27  Python                              0x00000001060743c1 PyEval_EvalCodeEx + 1583
    28  Python                              0x000000010607a4ae _PyEval_SliceIndex + 342
    29  Python                              0x000000010607730c PyEval_EvalFrameEx + 11609
    30  Python                              0x00000001060743c1 PyEval_EvalCodeEx + 1583
    31  Python                              0x0000000106073d8c PyEval_EvalCode + 54
    32  Python                              0x0000000106093a42 PyParser_ASTFromFile + 300
    33  Python                              0x0000000106093ae5 PyRun_FileExFlags + 133
    34  Python                              0x0000000106093634 PyRun_SimpleFileExFlags + 698
    35  Imagr                               0x0000000105fe9c1a main + 837
    36  libdyld.dylib                       0x00000001073c45ad start + 1
    37  ???                                 0x0000000000000001 0x0 + 1

**Comment by grahamgilbert** [comment]
Fixed in latest commit

**Comment by hamburg-macadmins** [comment]
still see the restart button problem, will check back tomorrow in an new imagr demo install at a customer site...

**Comment by grahamgilbert** [comment]
Are you sure you're on the latest version? I was using 0.0.4 today and it worked as expected.

**Comment by grahamgilbert** [comment]
Pretty sure this isn't an issue. Please reopen if that's not the case.
